### ISSUE TITLE
请问salt-broker支持双master吗

### ISSUE THREAD

**Issue by wenchangming211** [pengyao/salt-broker#11]
请问salt-broker支持双master吗

**Comment by pengyao** [comment]
salt-broker not support multi master

**Comment by wenchangming211** [comment]
okay 
thanks pengyao


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Peng Yao <notifications@github.com>
发送时间: 2019年7月8日 12:09
收件人: pengyao/salt-broker <salt-broker@noreply.github.com>
抄送: wenchangming211 <2568376869@qq.com>, Author <author@noreply.github.com>
主题: 回复：[pengyao/salt-broker] 请问salt-broker支持双master吗 (#11)




salt-broker not support multi master

**Comment by wenchangming211** [comment]
哈喽，请问经过salt-broker执行cp.push报这个错误，master和broker均配置了file_recv = True  file_recv_size_max = 100


[salt.loaded.int.module.cp][ERROR   ][20445] cp.push Failed transfer failed. Ensure master has 'file_recv' set to 'True' and that the file is not larger than the 'file_recv_size_max' setting on the master.




------------------ 原始邮件 ------------------
发件人: "Peng Yao"<notifications@github.com>;
发送时间: 2019年7月8日(星期一) 中午12:09
收件人: "pengyao/salt-broker"<salt-broker@noreply.github.com>;
抄送: "Jerry"<2568376869@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [pengyao/salt-broker] 请问salt-broker支持双master吗 (#11)




Closed #11.
