### ISSUE TITLE
Where does salt-broker run?

### ISSUE THREAD

**Issue by jalons** [pengyao/salt-broker#3]
Does salt-broker run on the syndic master of master in place of the usual salt-master process? It appears to want to bind to the master ports without flag reuse, so I'm having a hard time understanding how to set this up and run it to test it out.

We're trying to solve the same problems you reported in https://groups.google.com/d/msg/salt-users/RO0Fz2q_1KU/DAv_wK2r8-cJ so I'm interested in how to configure this up.

**Comment by pengyao** [comment]
salt-broker should run on the syndic node,  and stop syndic and master process before run.
